name: CI_Prod

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '**/README.md'
      - '**/dependabot.yml'
      - '.github/workflows/develop-func-ci.yml'
      - '.github/workflows/develop-func-deploy.yml'
      - 'docs/*'
    branches:
      - main

env:
  NODE_VERSION: '14.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Setup Node ${{ env.NODE_VERSION }} Environment'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 'Install Dependencies with Npm'
        run: |
          npm i -g npm
          npm install
